[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Netlify Forms configuration
[build.processing]
  skip_processing = false

# Email notifications for form submissions
[[plugins]]
  package = "@netlify/plugin-forms"

# Form handling
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
